### ISSUE TITLE
I want the server name to be displayed in the login and logout messages.

### ISSUE THREAD

**Issue by lolplay123** [NewAmazingPVP/ProxyPlayerNotify#3] opened 2024-05-04 14:29 UTC
Let me make a suggestion.
It would be useful to be able to display the server name at login and logout.

e.g. 
Steve joined the server (Logged in server: LOBBY)
Steve left the server (Last server: SURVIVAL)

Thank you very much!

**Comment by NewAmazingPVP** [comment] 2024-05-19 15:07
Sure, I could try to add this feature

**Comment by NewAmazingPVP** [comment] 2024-06-07 21:45
@lolplay123 Sorry for being so late, here is a [beta version](https://cdn.discordapp.com/attachments/1103464645899079743/1248754453708935282/ProxyPlayerNotify-betaservernames.jar?ex=6664d0b6&is=66637f36&hm=b4743f687b108b2bae7b1b990b44f11d7689e9cf512e2a101e418154887cfb12&). It would be great if you can test it out and let me know if it works as intended. Make sure to regenerate config.yml to see the new placeholders for the feature

**Comment by lolplay123** [comment] 2024-06-08 04:50
You're very busy, but thank you so much for creating the test plugin. I'll try it out right away!

**Comment by lolplay123** [comment] 2024-06-08 05:04
I regenerated the file and logged into the server, but nothing was displayed. Then, when I executed /reloadproxynotifyconfig, an error was output in the console.
https://pastebin.com/wD0A8rUp

**Comment by NewAmazingPVP** [comment] 2024-06-08 14:49
@lolplay123 I figured the issues out, try this [build](https://cdn.discordapp.com/attachments/1103464645899079743/1249012268818239598/ProxyPlayerNotify-bugFixes.jar?ex=6665c0d2&is=66646f52&hm=3772e93ecc52cfad78c340ac456d27d941552c9a24dc5ec8952746bcfd2368fc&) You will have to regenerate config.yml to fix the bugs

**Comment by lolplay123** [comment] 2024-06-09 06:40
Thank you for fixing the bug. The logs are now being displayed correctly. I'm not sure if this is by design, but it feels like the login message is being displayed slightly later than before.

**Comment by lolplay123** [comment] 2024-06-09 06:46
Also, the switch message format is set to %previousServer% and %connectedServer% when generating the file. After changing them to %last_server% and %server%, the logs were output correctly.

**Comment by NewAmazingPVP** [comment] 2024-06-09 21:57
Right now, messages are a bit delayed (1 second delay) because there is no way to get the server name directly when a player joins. Since this is beta, before I release the actual version, I will try to implement an alternative method that will reduce the delay as much as possible and be able to get the server name. But about the config.yml %previousServer% placeholder, I forgot to mention I did change it but hadn't fixed the config.yml. Thanks for noticing. Here is the [fixed one](https://discord.com/channels/1103464645420912671/1103464645899079743/1249481810967007282).

**Comment by lolplay123** [comment] 2024-06-10 10:51
The attached URL is a Discord URL, so I can't download the corrected file.

**Comment by NewAmazingPVP** [comment] 2024-06-10 16:08
@lolplay123 Sorry for that didn't notice, here is the right [link](https://cdn.discordapp.com/attachments/1103464645899079743/1249481810652430419/ProxyPlayerNotify-logicFixes.jar?ex=66681edd&is=6666cd5d&hm=c604691b56589c5fe56c841b29e8c1f05c481daa7a7af3264ef5cdcb5226c231&).

**Comment by NewAmazingPVP** [comment] 2024-06-10 16:24
I will close this issue for now. Keep an eye out for the new release coming out soon. I appreciate your help in testing this out, and feel free to reopen it if you find anything problematic.

**Closed as completed by NewAmazingPVP** 2024-06-10 16:24 UTC

**Comment by lolplay123** [comment] 2024-06-11 04:36
Thank you very much as well!

**Comment by lolplay123** [comment] 2024-06-11 06:21
[This URL](https://pastebin.com/bxgGFAzL) is the console error log that appeared when I logged in

**Comment by NewAmazingPVP** [comment] 2024-06-11 12:35
@lolplay123  Hey, by the way, I saw your message about the error with the null config private server setting. Here is a [build](https://cdn.discordapp.com/attachments/1103725182314614834/1250065069161713664/ProxyPlayerNotify-nullChecksConfig.jar?ex=66699551&is=666843d1&hm=f3e6d8530d8b9e59042845ae90808e9bfb4fd95cfb5d0be00360152034f2545c&) where if your private and disabled servers are set to null, it will check that it does not cause any errors.

**Comment by lolplay123** [comment] 2024-06-11 13:12
Thank you so much for the quick correction!
