### ISSUE TITLE
disabling switch messages

### ISSUE THREAD

**Issue by ethrydevelops** [NewAmazingPVP/ProxyPlayerNotify#1] opened 2023-06-05 03:30 UTC
can you please add a toggle so you can disable switch messages in config.yml? if i set it to "", it just leaves a blank space in chat

**Comment by NewAmazingPVP** [comment] 2023-06-05 14:37
hey there please download the latest release from here https://github.com/NewAmazingPVP/BungeePlayerNotify/releases/tag/v3.5 I have added a feature that if you just set message to "", it won't send any message. Do let me know if its working as intended and then Ill post this update on spigot

**Comment by NewAmazingPVP** [comment] 2023-06-06 01:44
Hey there, I released https://github.com/NewAmazingPVP/BungeePlayerNotify/releases/tag/v4.0 version which has even more features and I recommend you to download that. I'll close this issue now, but feel free to open another issue if something happens.

**Closed as completed by NewAmazingPVP** 2023-06-06 01:44 UTC
